/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.GameManager;
import Model.Game;
import Controller.GameController;
import javax.swing.JOptionPane;

public class MainView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());

    public MainView() { 
        initComponents();
        setupActions();
    }
    
private void setupActions() {
    
}    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Game Tracker");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Game Tracker");
        getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Admin");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Viewer");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String password = JOptionPane.showInputDialog(this,
        "Enter Admin Password:",
        "Admin Access",
        JOptionPane.QUESTION_MESSAGE);
    
    System.out.println("Admin button clicked. Password entered: " + password);
    
    if (password != null && password.equals("admin123")) {
        System.out.println("Password correct. Creating AdminDashboard...");
        
        // Create GameManager
        Model.GameManager gameManager = new Model.GameManager();

        // Add sample games
            gameManager.addGame(new Game("Minecraft", "PC", 2011, "Adventure"));
            gameManager.addGame(new Game("The Last of Us", "PlayStation", 2013, "Action"));
            gameManager.addGame(new Game("Super Mario Odyssey", "Nintendo Switch", 2017, "Platformer"));
            gameManager.addGame(new Game("Skyrim", "PC", 2011, "RPG"));
            gameManager.addGame(new Game("Dark Souls", "PlayStation", 2008, "Action"));
            gameManager.addGame(new Game("Tetris", "Mobile", 1984, "Puzzle"));
            gameManager.addGame(new Game("FIFA 23", "Multiplatform", 2022, "Sports"));
            gameManager.addGame(new Game("Call of Duty", "PC", 2003, "FPS"));
            gameManager.addGame(new Game("Among Us", "Mobile", 2018, "Party"));
            gameManager.addGame(new Game("Grand Theft Auto V", "PlayStation", 2013, "Action"));
        System.out.println("Added " + gameManager.getAllGames().size() + " games to GameManager");

        try {
            // Open Admin Dashboard
            System.out.println("Creating AdminDashboard object...");
            AdminDashboard adminDashboard = new AdminDashboard(gameManager);
            System.out.println("AdminDashboard created. Setting visible...");
            adminDashboard.setVisible(true);
            System.out.println("AdminDashboard should be visible now.");

            // Close welcome screen
            this.dispose();
            System.out.println("MainView closed.");
            
        } catch (Exception e) {
            System.out.println("ERROR creating AdminDashboard: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error opening admin dashboard: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } else if (password != null) {
        System.out.println("Password incorrect: " + password);
        JOptionPane.showMessageDialog(this,
            "Invalid password. Access denied.",
            "Admin Access Denied",
            JOptionPane.ERROR_MESSAGE);
    } else {
        System.out.println("User cancelled password dialog");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            jButton2.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            // Create and show Viewer Dashboard
            ViewerView viewerDashboard = new ViewerView();
            
            // Create Model with sample data
            GameManager gameManager = new GameManager();
            // Add sample games for testing
            gameManager.addGame(new Game("Minecraft", "PC", 2011, "Adventure"));
            gameManager.addGame(new Game("The Last of Us", "PlayStation", 2013, "Action"));
            gameManager.addGame(new Game("Super Mario Odyssey", "Nintendo Switch", 2017, "Platformer"));
            gameManager.addGame(new Game("Skyrim", "PC", 2011, "RPG"));
            gameManager.addGame(new Game("Dark Souls", "PlayStation", 2008, "Action"));
            gameManager.addGame(new Game("Tetris", "Mobile", 1984, "Puzzle"));
            gameManager.addGame(new Game("FIFA 23", "Multiplatform", 2022, "Sports"));
            gameManager.addGame(new Game("Call of Duty", "PC", 2003, "FPS"));
            gameManager.addGame(new Game("Among Us", "Mobile", 2018, "Party"));
            gameManager.addGame(new Game("Grand Theft Auto V", "PlayStation", 2013, "Action"));
            
            // Create Controller
            GameController controller = new GameController(gameManager, viewerDashboard);
            
            
            // Set window properties
            viewerDashboard.setVisible(true);
            viewerDashboard.setSize(900, 700);
            viewerDashboard.setLocationRelativeTo(null);
            viewerDashboard.setTitle("Game Tracker - Viewer Dashboard");
            
            // Close welcome screen
            MainView.this.dispose();
        }
    });
    }//GEN-LAST:event_jButton2ActionPerformed

     public javax.swing.JButton getAdminButton() {
        return jButton1;
    }
    
    public javax.swing.JButton getViewerButton() {
        return jButton2;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {new MainView().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
